### ISSUE TITLE
Other FrostBite games?

### ISSUE THREAD

**Issue by SafaAlfulaij** [zeroKilo/MEAExplorerWV#4]
Hello mr WV!
I'd like to thank you very much for the amount of work to make these tools.
I was wondering, if the current tool can open other FrostBite-based games, by small tweaks, if you have the time and effort and the desire.
I tried NeedForSpeed Rivals and the tool showed some fast progress bars moving, but stopped at the end.
The game has a similar game folder structure, but many files (other than some like localization) are compressed into big CAS files in Data folder. (I saw the game folder structure of `Mass Effect Andromeda`.)
I was able to decompress the files using `BF_Four_Python_Scripts` and even the `ebx` to `txt`, but I want to repack them, and I have, unfortunately, zero knowledge about how to do that, as I'm just a translator.
These are the `cas.cat`, `layout.toc` and `initFS_Win32` files: [catLayoutFS.zip](https://github.com/zeroKilo/MEAExplorerWV/files/1016113/catLayoutFS.zip)
Do you think it will be a simple thing?
Forgive me, I know you hate this kind of people! 😓 
_EDIT_: And yes, I know I should post this on ZenHax, but I thought of posting here first to get your opinion :)

```
Loading FS...
Selected path = C:\Users\Safa Alfulaij\Documents\Games\Need for Speed(TM) Rivals\NFS14.exe
Loading TOC files...
 Loading Data\layout.toc
 Loading Data\Win32\Chunks0.toc
 Loading Data\Win32\ChunksAudio.toc
 Loading Data\Win32\ChunksAudioStream.toc
 Loading Data\Win32\Cutscenes.toc
 Loading Data\Win32\Globals.toc
 Loading Data\Win32\HD.toc
 Loading Data\Win32\UI.toc
 Loading Data\Win32\Vehicles0.toc
 Loading Data\Win32\Vehicles1.toc
 Loading Data\Win32\Vehicles2.toc
 Loading Data\Win32\Videos.toc
 Loading Data\Win32\Levels\FrontEnd\FrontEnd.toc
 Loading Data\Win32\Levels\HP2\HP2.toc
 Loading Data\Win32\Levels\LoadingScreenHost\LoadingScreenHost.toc
 Loading Data\Win32\Loc\en.toc
 Loading Update\Patch\Data\layout.toc
 Loading Update\Patch\Data\Win32\Globals.toc
 Loading Update\Patch\Data\Win32\UI.toc
 Loading Update\Patch\Data\Win32\Levels\FrontEnd\FrontEnd.toc
 Loading Update\Patch\Data\Win32\Levels\HP2\HP2.toc
 Loading Update\Patch\Data\Win32\Loc\br.toc
 Loading Update\Patch\Data\Win32\Loc\de.toc
 Loading Update\Patch\Data\Win32\Loc\en.toc
 Loading Update\Patch\Data\Win32\Loc\es.toc
 Loading Update\Patch\Data\Win32\Loc\fr.toc
 Loading Update\Patch\Data\Win32\Loc\it.toc
 Loading Update\Patch\Data\Win32\Loc\ja.toc
 Loading Update\Patch\Data\Win32\Loc\nl.toc
 Loading Update\Patch\Data\Win32\Loc\pl.toc
 Loading Update\Patch\Data\Win32\Loc\ru.toc
 Loading Update\Patch\Data\Win32\Loc\zh.toc
Loading CAT files...
 Loading Data\cas.cat
 Loading Update\Patch\Data\cas.cat
Loading initfs_Win32 from C:\Users\Safa Alfulaij\Documents\Games\Need for Speed(TM) Rivals\data\initfs_Win32...found!
ERROR: unknown field type 0x12
Stacktrace:    at MEAExplorerWV.DBObject.Field..ctor(Stream s)
   at MEAExplorerWV.DBObject.ReadFields(Stream s)
   at MEAExplorerWV.TOC..ctor(Byte[] data)
   at MEAExplorerWV.FS.TOCEntry..ctor(String path, String display, Byte[] input)
   at MEAExplorerWV.Form1.LoadFS(Boolean showDialog)
```

<details> 
  <summary>Filelist</summary>
   <p>

Need for Speed(TM) Rivals\Data\cas.cat
Need for Speed(TM) Rivals\Data\cas_01.cas
Need for Speed(TM) Rivals\Data\cas_02.cas
Need for Speed(TM) Rivals\Data\cas_03.cas
Need for Speed(TM) Rivals\Data\cas_04.cas
Need for Speed(TM) Rivals\Data\cas_05.cas
Need for Speed(TM) Rivals\Data\cas_06.cas
Need for Speed(TM) Rivals\Data\cas_07.cas
Need for Speed(TM) Rivals\Data\cas_08.cas
Need for Speed(TM) Rivals\Data\initfs_Win32
Need for Speed(TM) Rivals\Data\layout.toc
Need for Speed(TM) Rivals\Data\Win32\Chunks0.sb
Need for Speed(TM) Rivals\Data\Win32\Chunks0.toc
Need for Speed(TM) Rivals\Data\Win32\ChunksAudio.sb
Need for Speed(TM) Rivals\Data\Win32\ChunksAudio.toc
Need for Speed(TM) Rivals\Data\Win32\ChunksAudioStream.sb
Need for Speed(TM) Rivals\Data\Win32\ChunksAudioStream.toc
Need for Speed(TM) Rivals\Data\Win32\Cutscenes.sb
Need for Speed(TM) Rivals\Data\Win32\Cutscenes.toc
Need for Speed(TM) Rivals\Data\Win32\frostbite.bms
Need for Speed(TM) Rivals\Data\Win32\Globals.sb
Need for Speed(TM) Rivals\Data\Win32\Globals.toc
Need for Speed(TM) Rivals\Data\Win32\HD.sb
Need for Speed(TM) Rivals\Data\Win32\HD.toc
Need for Speed(TM) Rivals\Data\Win32\UI.sb
Need for Speed(TM) Rivals\Data\Win32\UI.toc
Need for Speed(TM) Rivals\Data\Win32\Vehicles0.sb
Need for Speed(TM) Rivals\Data\Win32\Vehicles0.toc
Need for Speed(TM) Rivals\Data\Win32\Vehicles1.sb
Need for Speed(TM) Rivals\Data\Win32\Vehicles1.toc
Need for Speed(TM) Rivals\Data\Win32\Vehicles2.sb
Need for Speed(TM) Rivals\Data\Win32\Vehicles2.toc
Need for Speed(TM) Rivals\Data\Win32\Videos.sb
Need for Speed(TM) Rivals\Data\Win32\Videos.toc
Need for Speed(TM) Rivals\Data\Win32\Levels\FrontEnd\FrontEnd.sb
Need for Speed(TM) Rivals\Data\Win32\Levels\FrontEnd\FrontEnd.toc
Need for Speed(TM) Rivals\Data\Win32\Levels\HP2\HP2.sb
Need for Speed(TM) Rivals\Data\Win32\Levels\HP2\HP2.toc
Need for Speed(TM) Rivals\Data\Win32\Levels\LoadingScreenHost\LoadingScreenHost.sb
Need for Speed(TM) Rivals\Data\Win32\Levels\LoadingScreenHost\LoadingScreenHost.toc
Need for Speed(TM) Rivals\Data\Win32\Loc\en.sb
Need for Speed(TM) Rivals\Data\Win32\Loc\en.toc
Need for Speed(TM) Rivals\Update\Patch\package.mft
Need for Speed(TM) Rivals\Update\Patch\Data\cas.cat
Need for Speed(TM) Rivals\Update\Patch\Data\cas_01.cas
Need for Speed(TM) Rivals\Update\Patch\Data\initfs_Win32
Need for Speed(TM) Rivals\Update\Patch\Data\layout.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Globals.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Globals.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\UI.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\UI.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Levels\FrontEnd\FrontEnd.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Levels\FrontEnd\FrontEnd.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Levels\HP2\HP2.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Levels\HP2\HP2.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\br.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\br.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\de.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\de.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\en.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\en.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\es.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\es.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\fr.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\fr.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\it.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\it.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\ja.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\ja.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\nl.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\nl.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\pl.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\pl.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\ru.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\ru.toc
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\zh.sb
Need for Speed(TM) Rivals\Update\Patch\Data\Win32\Loc\zh.toc
</p> 
</details>

**Comment by zeroKilo** [comment]
there are plenty of games this could work on, but you would have to rewrite the main tool to take all quirks into account and I dont intend to port this. also once kiwidogs rime is released, this tool and any port would be useless anyway, so this seems pointless, sry

greetz

**Comment by SafaAlfulaij** [comment]
Hi again :-)
I'm still having this in my mind, unfortunately.
I figured out that for localizing the game I'll need to change 2 pairs (hopefully) of toc/sb files only.
These are: 3 ebx, 1 res, 1-2 chunks, and the toc files to fix the offsets/sizes.
I was able to extract them, but not to recompile them.
If you could just share with me the code of compressing/recompiling these files only, I would really appreciate that. Or maybe a documentation or so.
I do understand that you prefer to keep the main tool code yourself, as I know that it took a huge amount of time to build it up till it reached it's current form. If so, then hope you the best!
And really sorry for the inconvenience!

**Comment by zeroKilo** [comment]
https://github.com/zeroKilo/DAIToolsWV do you recognize this github account? yeah, its mine, and its open source, and has all the code thats currently not release/rewritten for mea as opensource, but feel free to do so

**Comment by SafaAlfulaij** [comment]
Wow man, calm down.
Thank. I forgot to recheck it again when I questioned, because I checked it once back in time.

**Comment by zeroKilo** [comment]
if you were able to extract them, you must know that the data is stored in cas files, and stored as blocks, which "can" be compressed, you can simply save them uncompressed back. import is simply overwriting the offset/size/casnr in the cat file for that entry with its new location, like f.e. a new cas file or appended to an existing one... I am calm, but im a researcher, not community moderator, also you dont spend time helping with my tools either and I already have enough to do with that...
